### ISSUE TITLE
Compilation of  table_top_segmentation

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/OccludedObjectRecognition#1]
I get this error when compiling the package

home/mike/catkin_ws/src/OccludedObjectRecognition/occluded_object_recognition/src/table_top_segmentation.cpp:19:55: fatal error: pcl/features/moment_of_inertia_estimation.h: No such file or directory
 #include <pcl/features/moment_of_inertia_estimation.h>

Should I require some special pcl version? If so, it should be on the CMakeLists.txt.

**Comment by rarrais** [comment]
@miguelriemoliveira can you try re-compiling after the last commit?

**Comment by miguelriemoliveira** [comment]
I had to change the CMakeLists.txt to recompile the node again, but now it works. Thanks.

I am closing the issue.
